import { pdf, Document, Page, Text, View, StyleSheet, Image as PDFImage } from '@react-pdf/renderer';
import { saveAs } from 'file-saver';
import html2canvas from 'html2canvas';

// Keep the background plain white or dark depending on target, react-pdf handles exact rgb rendering
const styles = StyleSheet.create({
  page: { backgroundColor: '#1e1e1e', padding: 30, fontFamily: 'Helvetica' },
  header: { fontSize: 24, marginBottom: 10, color: '#00ff88', fontWeight: 'bold' },
  subheader: { fontSize: 14, marginBottom: 20, color: '#888888' },
  row: { flexDirection: 'row', paddingVertical: 8, borderBottom: '1pt solid #333333' },
  cell: { flex: 1, fontSize: 12, color: '#ffffff' },
  footer: { marginTop: 40, fontSize: 10, color: '#666666', textAlign: 'center' }
});

const ReportFormat = ({ type, data }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View><Text style={styles.header}>🎯 HABIT TRACKER - {type.toUpperCase()} REPORT</Text></View>
      <View><Text style={styles.subheader}>{data.userName} | {data.date || data.weekRange || data.monthName}</Text></View>
      
      {data.chartImage && (
        <View style={{ marginBottom: 20 }}>
          <PDFImage src={data.chartImage} style={{ width: '100%', height: 200 }} />
        </View>
      )}

      <View style={styles.row}>
        <Text style={{...styles.cell, color: '#00ff88'}}>Habit Name</Text>
        <Text style={{...styles.cell, color: '#00ff88'}}>Status</Text>
      </View>

      {data.habits?.map((h, i) => (
        <View key={i} style={styles.row}>
          <Text style={styles.cell}>{h.name}</Text>
          <Text style={styles.cell}>{h.percent !== undefined ? `${h.percent}%` : (h.completed ? '✅ Done' : '❌ Missed')}</Text>
        </View>
      ))}

      <View><Text style={styles.footer}>Generated by Habit Tracker</Text></View>
    </Page>
  </Document>
);

export async function downloadPDF(type, data, chartRef) {
  try {
    if (chartRef?.current) {
      // capture high fidelity canvas representing our web charts
      const canvas = await html2canvas(chartRef.current, { backgroundColor: '#0d1117', scale: 2 });
      data.chartImage = canvas.toDataURL('image/png');
    }
    const blob = await pdf(<ReportFormat type={type} data={data} />).toBlob();
    saveAs(blob, `HabitTracker_${type}_${new Date().toISOString().split('T')[0]}.pdf`);
  } catch (err) {
    console.error('PDF generation error', err);
    throw err;
  }
}
