import { Document, Paragraph, TextRun, Packer } from 'docx';
import { saveAs } from 'file-saver';
import { format } from 'date-fns';

export async function downloadDOCX(type, data) {
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({ children: [new TextRun({ text: `HABIT TRACKER - ${type.toUpperCase()} REPORT`, bold: true, size: 32 })] }),
        new Paragraph({ children: [new TextRun({ text: `User: ${data.userName}`, size: 24 })] }),
        new Paragraph({ children: [new TextRun({ text: `Timeframe: ${data.date || data.weekRange || data.monthName}`, size: 24 })] }),
        new Paragraph({ text: "" }),
        ...data.habits.map(h => 
          new Paragraph({ children: [new TextRun({ text: `• ${h.name} : ${h.percent || (h.completed ? '100' : '0')}% completed`, size: 24 })] })
        ),
        new Paragraph({ text: "" }),
        new Paragraph({ children: [new TextRun({ text: `Generated by Habit Tracker on ${format(new Date(), 'PPP')}`, size: 20, italics: true })] })
      ]
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `HabitTracker_${type}_${format(new Date(), 'yyyy-MM-dd')}.docx`);
}
